export const IMAGES = {
  quizScience: require("../../assets/images/content/image_quiz_science.png"),
  quizSport: require("../../assets/images/content/image_quiz_sport.png"),

  sport1: require("../../assets/images/quizimage/sport/Quiz-1.jpg"),
  sport2: require("../../assets/images/quizimage/sport/Quiz-2.jpeg"),
  sport4: require("../../assets/images/quizimage/sport/Quiz-4.jpeg"),
  sport5: require("../../assets/images/quizimage/sport/Quiz-5.jpeg"),
  sport6: require("../../assets/images/quizimage/sport/Quiz-6.jpeg"),
  sport7: require("../../assets/images/quizimage/sport/Quiz-7.jpeg"),
  sport8: require("../../assets/images/quizimage/sport/Quiz-8.jpeg"),
  sport9: require("../../assets/images/quizimage/sport/Quiz-9.jpeg"),
  sport10: require("../../assets/images/quizimage/sport/Quiz-10.jpg"),
  sport11: require("../../assets/images/quizimage/sport/Quiz-11.jpeg"),
  sport12: require("../../assets/images/quizimage/sport/Quiz-12.jpg"),
  sport13: require("../../assets/images/quizimage/sport/Quiz-13.jpg"),
  sport14: require("../../assets/images/quizimage/sport/Quiz-14.jpeg"),
  sport15: require("../../assets/images/quizimage/sport/Quiz-15.jpeg"),
  sport16: require("../../assets/images/quizimage/sport/Quiz-16.jpg"),
  sport17: require("../../assets/images/quizimage/sport/Quiz-17.jpeg"),
  sport18: require("../../assets/images/quizimage/sport/Quiz-18.jpeg"),
  sport19: require("../../assets/images/quizimage/sport/Quiz-19.jpeg"),
  sport20: require("../../assets/images/quizimage/sport/Quiz-20.jpeg"),

  science1: require("../../assets/images/quizimage/science/Quiz-1.jpg"),
  science2: require("../../assets/images/quizimage/science/Quiz-2.jpg"),
  science4: require("../../assets/images/quizimage/science/Quiz-4.jpeg"),
  science5: require("../../assets/images/quizimage/science/Quiz-5.jpg"),
  science6: require("../../assets/images/quizimage/science/Quiz-6.jpeg"),
  science7: require("../../assets/images/quizimage/science/Quiz-7.jpeg"),
  science8: require("../../assets/images/quizimage/science/Quiz-8.jpeg"),
  science9: require("../../assets/images/quizimage/science/Quiz-9.jpeg"),
  science10: require("../../assets/images/quizimage/science/Quiz-10.jpeg"),
  science11: require("../../assets/images/quizimage/science/Quiz-11.jpeg"),
  science12: require("../../assets/images/quizimage/science/Quiz-12.jpeg"),
  science13: require("../../assets/images/quizimage/science/Quiz-13.jpeg"),
  science14: require("../../assets/images/quizimage/science/Quiz-14.jpeg"),
  science15: require("../../assets/images/quizimage/science/Quiz-15.jpeg"),
  science16: require("../../assets/images/quizimage/science/Quiz-16.jpeg"),
  science17: require("../../assets/images/quizimage/science/Quiz-17.jpeg"),
  science18: require("../../assets/images/quizimage/science/Quiz-18.jpeg"),
  science19: require("../../assets/images/quizimage/science/Quiz-19.jpeg"),
  science20: require("../../assets/images/quizimage/science/Quiz-20.jpeg"),

  math1: require("../../assets/images/quizimage/math/Quiz-1.jpg"),
  math2: require("../../assets/images/quizimage/math/Quiz-2.jpg"),
  math3: require("../../assets/images/quizimage/math/Quiz-3.jpg"),
  math4: require("../../assets/images/quizimage/math/Quiz-4.jpg"),
  math5: require("../../assets/images/quizimage/math/Quiz-5.jpg"),
  math6: require("../../assets/images/quizimage/math/Quiz-6.jpg"),
  math7: require("../../assets/images/quizimage/math/Quiz-7.jpg"),
  math8: require("../../assets/images/quizimage/math/Quiz-8.jpg"),
  math9: require("../../assets/images/quizimage/math/Quiz-9.jpg"),
  math10: require("../../assets/images/quizimage/math/Quiz-10.jpg"),
  math11: require("../../assets/images/quizimage/math/Quiz-11.jpg"),
  math12: require("../../assets/images/quizimage/math/Quiz-12.jpg"),
  math13: require("../../assets/images/quizimage/math/Quiz-13.jpg"),
  math14: require("../../assets/images/quizimage/math/Quiz-14.jpg"),
  math15: require("../../assets/images/quizimage/math/Quiz-15.jpg"),
  math16: require("../../assets/images/quizimage/math/Quiz-16.jpg"),
  math17: require("../../assets/images/quizimage/math/Quiz-17.jpg"),
  math18: require("../../assets/images/quizimage/math/Quiz-18.jpg"),
  math19: require("../../assets/images/quizimage/math/Quiz-19.jpg"),
  math20: require("../../assets/images/quizimage/math/Quiz-20.jpg"),

  animal1: require("../../assets/images/quizimage/animal/Quiz-1.jpg"),
  animal2: require("../../assets/images/quizimage/animal/Quiz-2.jpg"),
  animal3: require("../../assets/images/quizimage/animal/Quiz-3.jpg"),
  animal4: require("../../assets/images/quizimage/animal/Quiz-4.jpg"),
  animal5: require("../../assets/images/quizimage/animal/Quiz-5.jpg"),
  animal6: require("../../assets/images/quizimage/animal/Quiz-6.jpg"),
  animal7: require("../../assets/images/quizimage/animal/Quiz-7.jpg"),
  animal8: require("../../assets/images/quizimage/animal/Quiz-8.jpg"),
  animal9: require("../../assets/images/quizimage/animal/Quiz-9.jpg"),
  animal10: require("../../assets/images/quizimage/animal/Quiz-10.jpg"),
  animal11: require("../../assets/images/quizimage/animal/Quiz-11.jpg"),
  animal12: require("../../assets/images/quizimage/animal/Quiz-12.jpg"),
  animal13: require("../../assets/images/quizimage/animal/Quiz-13.jpg"),
  animal14: require("../../assets/images/quizimage/animal/Quiz-14.jpg"),
  animal15: require("../../assets/images/quizimage/animal/Quiz-15.jpg"),
  animal16: require("../../assets/images/quizimage/animal/Quiz-16.jpg"),
  animal17: require("../../assets/images/quizimage/animal/Quiz-17.jpg"),
  animal18: require("../../assets/images/quizimage/animal/Quiz-18.jpg"),
  animal19: require("../../assets/images/quizimage/animal/Quiz-19.jpg"),
  animal20: require("../../assets/images/quizimage/animal/Quiz-20.jpg"),
};

export const ICONS = {
  checkmarkGreen: require("../../assets/images/icons/icon_checkmark_green.png"),
  close: require("../../assets/images/icons/icon_close.png"),
  coinScore: require("../../assets/images/icons/icon_coin_score.png"),
  googleG: require("../../assets/images/icons/icon_google_g.png"),
  listAnimals: require("../../assets/images/icons/icon_list_animals.png"),
  listMath: require("../../assets/images/icons/icon_list_math.png"),
  listOther: require("../../assets/images/icons/icon_list_other.png"),
  listScience: require("../../assets/images/icons/icon_list_science.png"),
  nextArrow: require("../../assets/images/icons/icon_next_arrow.png"),
  tabHome: require("../../assets/images/icons/icon_tab_home.png"),
  tabQuiz: require("../../assets/images/icons/icon_tab_quiz.png"),
  tabRank: require("../../assets/images/icons/icon_tab_rank.png"),
};

export const ILLUSTRATIONS = {
  coinLarge: require("../../assets/images/illustrations/illust_coin_large.png"),
  coinMedium: require("../../assets/images/illustrations/illust_coin_medium.png"),
  coinSmall: require("../../assets/images/illustrations/illust_coin_small.png"),
  onboardingMain: require("../../assets/images/illustrations/illust_onboarding_main.png"),
  pinkBook: require("../../assets/images/illustrations/illust_pink_book.png"),
  togaBooks: require("../../assets/images/illustrations/illust_toga_books.png"),
};
