import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.homeBackground,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: COLORS.homeBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    fontSize: 18,
    color: COLORS.textDark,
    fontWeight: "600",
  },
  scrollContent: {
    paddingTop: 60,
    paddingBottom: 100,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    marginBottom: 25,
  },
  headerTextWrapper: {
    flex: 1,
    marginRight: 10,
  },
  greeting: {
    fontSize: 18,
    fontWeight: "500",
    color: "#46557B",
    marginBottom: 5,
  },
  subGreeting: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#46557B",
    lineHeight: 30,
  },
  coinContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#927AFF",
    paddingLeft: 14,
    paddingRight: 6,
    paddingVertical: 6,
    borderRadius: 20,
    flexShrink: 0,
  },
  coinText: {
    fontSize: 15,
    fontWeight: "bold",
    color: COLORS.white,
    marginRight: 6,
  },
  coinIconWrapper: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
  },
  coinIcon: {
    width: 18,
    height: 18,
  },
  categoryScrollContent: {
    paddingRight: 20,
  },
  categoryCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    overflow: "hidden",
    marginRight: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  categoryImageContainer: {
    width: "100%",
    height: 140,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  categoryContent: {
    padding: 16,
  },
  categoryTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#46557B",
    marginBottom: 8,
  },
  categoryQuestions: {
    fontSize: 13,
    color: "#46557B",
  },
  progressBarContainer: {
    height: 6,
    backgroundColor: "#E5E7EB",
    borderRadius: 3,
    overflow: "hidden",
    flex: 1,
    marginLeft: 12,
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  progressBar: {
    height: "100%",
    borderRadius: 3,
  },
  paginationDots: {
    flexDirection: "row",
    justifyContent: "flex-start",
    paddingLeft: 20,
    alignItems: "center",
    marginTop: 15,
    marginBottom: 25,
    gap: 4,
  },
  dot: {
    width: 24,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#E0E7FF",
  },
  dotActive: {
    width: 24,
    backgroundColor: "#6366F1",
  },
  section: {
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: "bold",
    color: "#46557B",
    marginBottom: 15,
  },
  gameCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    marginHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  gameIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  gameIcon: {
    width: 50,
    height: 50,
  },
  gameInfo: {
    flex: 1,
  },
  gameTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#46557B",
    marginBottom: 3,
  },
  gameQuestions: {
    fontSize: 12,
    color: "#46557B",
  },
  progressCircleContainer: {
    marginLeft: 10,
    width: 52,
    height: 52,
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    paddingVertical: 10,
    paddingHorizontal: 40,
    justifyContent: "space-around",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 5,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  navIcon: {
    width: 30,
    height: 30,
    tintColor: "#9CA3AF",
  },
  bottomSpacing: {
    height: 20,
  },
});
