import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../constants/colors";
import { FONT } from "../constants/fontfamily";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  decorativeContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  togaTop: {
    position: "absolute",
    width: 130,
    height: 130,
    top: 30,
    left: 0,
    opacity: 1,
  },
  coinTopCenter: {
    position: "absolute",
    width: 60,
    height: 60,
    top: height * 0.07,
    left: "38%",
    opacity: 1,
  },
  coinTopRight: {
    position: "absolute",
    width: 130,
    height: 130,
    top: 0,
    right: 0,
    opacity: 1,
  },
  coinBottomLeft: {
    position: "absolute",
    width: 60,
    height: 60,
    bottom: height * 0.4,
    left: "10%",
    opacity: 1,
  },
  coinMidRight: {
    position: "absolute",
    width: 50,
    height: 50,
    top: height * 0.29,
    right: "16%",
    opacity: 1,
  },
  pinkBookBottom: {
    position: "absolute",
    width: 130,
    height: 80,
    bottom: height * 0.36,
    right: "5%",
    opacity: 1,
  },
  loginContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: height * 0.12,
    paddingBottom: height * 0.08,
    paddingHorizontal: 30,
  },
  contentInputName: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-around",
    paddingTop: height * 0.12,
    paddingBottom: height * 0.08,
    paddingHorizontal: 30,
  },
  illustrationWrapper: {
    width: width * 0.9,
    height: height * 0.45,
    alignItems: "center",
    justifyContent: "center",
    marginTop: height * 0.03,
  },
  illustration: {
    width: "100%",
    height: "100%",
  },
  textWrapper: {
    width: "100%",
  },
  title: {
    fontSize: 35,
    color: COLORS.white,
    textAlign: "left",
    lineHeight: 40,
    fontFamily: FONT.medium,
  },
  subtitle: {
    fontSize: 18,
    color: COLORS.white,
    marginTop: 12,
    opacity: 0.92,
    lineHeight: 22,
    fontFamily: FONT.medium,
  },
  boldText: {
    fontFamily: FONT.bold,
  },
  buttonSection: {
    width: "100%",
    alignItems: "center",
  },
  googleButton: {
    flexDirection: "row",
    backgroundColor: COLORS.white,
    paddingVertical: 20,
    width: "100%",
    borderRadius: 35,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  googleIcon: {
    width: 24,
    height: 24,
    position: "absolute",
    left: 20,
  },
  googleButtonText: {
    fontSize: 16,
    fontFamily: FONT.semiBold,
    color: COLORS.textDark,
    letterSpacing: 0.8,
    textAlign: "center",
    flex: 1,
  },
  getStartedLink: {
    marginTop: 20,
    alignItems: "center",
  },
  getStartedLinkText: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.white,
    textDecorationLine: "underline",
    fontFamily: FONT.semiBold,
  },
  inputCard: {
    backgroundColor: COLORS.white,
    borderRadius: 30,
    padding: 30,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  cardTitle: {
    fontSize: 24,
    fontFamily: FONT.bold,
    color: COLORS.textDark,
    marginBottom: 10,
    textAlign: "center",
  },
  cardSubtitle: {
    fontSize: 14,
    color: COLORS.textDark,
    marginBottom: 20,
    textAlign: "center",
    fontFamily: FONT.medium,
  },
  input: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.primary,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 20,
    fontSize: 16,
    color: COLORS.textDark,
    marginBottom: 20,
    fontFamily: FONT.medium,
  },
  getStartedButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 30,
    paddingVertical: 16,
    alignItems: "center",
  },
  getStartedText: {
    fontSize: 16,
    color: COLORS.white,
    letterSpacing: 0.5,
    fontFamily: FONT.semiBold,
  },
});
